// <auto-generated />
namespace ePunkt.IssueTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class MissingIndex : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MissingIndex));
        
        string IMigrationMetadata.Id
        {
            get { return "201409091744577_MissingIndex"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
