// <auto-generated />
namespace ePunkt.IssueTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserPassword : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserPassword));
        
        string IMigrationMetadata.Id
        {
            get { return "201310161048018_UserPassword"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
